name: CI

on: [push]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v1
          - name: Run yarn install
            run: yarn install
    test:
      name: Tests
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Run tests
          run: yarn test --watchAll=false
